// few comments on side lines are generated by CoPilot for a clearer picture...
// to build the project refer the readme instructions

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
#include <array>

// ─── constants ─────
static constexpr uint64_t DRAM_SIZE = 64ULL * 1024 * 1024;   // 64 MiB
static constexpr uint64_t DRAM_BASE = 0x80000000ULL;         // linker addr
static constexpr uint64_t UART_ADDR = 0x10000000ULL;         // MMIO putc

// ─── Memory Simulation ───
class Memory {
public:
    explicit Memory(uint64_t sz = DRAM_SIZE) : data(sz, 0) {}

    template<typename T>
    T load(uint64_t addr) const {
        if (addr - DRAM_BASE >= data.size()) trap("load OOB");
        T v; std::memcpy(&v, &data[addr - DRAM_BASE], sizeof(T));
        return v;
    }
    template<typename T>
    void store(uint64_t addr, T v) {
        if (addr == UART_ADDR && sizeof(T) == 1) { std::putchar(char(v)); return; }
        if (addr - DRAM_BASE >= data.size()) trap("store OOB");
        std::memcpy(&data[addr - DRAM_BASE], &v, sizeof(T));
    }
    std::vector<uint8_t>& raw() { return data; }

private:
    [[noreturn]] static void trap(const char* msg){
        std::fprintf(stderr,"MEM: %s\n",msg); std::exit(1);
    }
    std::vector<uint8_t> data;
};

// ─── ELF loader ───
static uint64_t load_elf(const char* path, Memory& mem)
{
    std::ifstream f(path,std::ios::binary);
    if(!f){ std::perror("elf"); std::exit(1); }
    std::vector<char> buf((std::istreambuf_iterator<char>(f)),{});
    auto rd32=[&](size_t o){ return *reinterpret_cast<uint32_t*>(&buf[o]); };
    auto rd64=[&](size_t o){ return *reinterpret_cast<uint64_t*>(&buf[o]); };

    if(buf[4]!=2){ std::fprintf(stderr,"not 64-bit ELF\n"); std::exit(1); }
    uint16_t phsz  = *reinterpret_cast<uint16_t*>(&buf[54]);
    uint16_t phnum = *reinterpret_cast<uint16_t*>(&buf[56]);
    uint64_t phoff = rd64(32), entry = rd64(24);

    for(uint16_t i=0;i<phnum;++i){
        size_t off = phoff + i*phsz;
        if(rd32(off) != 1) continue;            // PT_LOAD
        uint64_t ofs=rd64(off+8), vaddr=rd64(off+16), sz=rd64(off+32);
        std::memcpy(&mem.raw()[vaddr-DRAM_BASE], &buf[ofs], sz);
    }
    return entry;
}

// ─── CPU core ────
class CPU {
public:
    CPU(Memory& m, uint64_t pc0) : mem(m), pc(pc0) { regs.fill(0); }

    bool step() {
        uint32_t ins = mem.load<uint32_t>(pc);
        pc += 4;

        // ---- cycles ----
        cycles += base_cost(ins);
        if (is_spill_like(ins)) cycles += spill_penalty;

        decode_execute(ins);
        regs[0] = 0;
        return running;
    }
    uint64_t get_cycles() const { return cycles; }

    // adding penalty to the cycles for the behavioral model (since it's a simulation)
    static int spill_penalty;               // default below
    static uint8_t base_cost(uint32_t ins){ // 1-or-2-cycle latency table
        switch(ins & 0x7F){
        case 0b0000011: case 0b0100011: return 2;   // LD / ST
        default:                                   // ALU, branch, etc.
            return 1;
        }
    }

private:
    uint64_t cycles = 0;

    // RISCV-ISA
    static uint32_t fn3(uint32_t i){ return (i>>12)&7; }
    static uint32_t fn7(uint32_t i){ return i>>25;     }
    static uint32_t rd (uint32_t i){ return (i>>7)&31; }
    static uint32_t rs1(uint32_t i){ return (i>>15)&31;}
    static uint32_t rs2(uint32_t i){ return (i>>20)&31;}
    static int64_t  sx(uint64_t v,int b){ return int64_t(v<<(64-b))>>(64-b);}
    static uint64_t sx32(int32_t v){ return uint64_t(int64_t(v)); }

    static int32_t imm_I(uint32_t i){ return int32_t(i)>>20; }
    static int32_t imm_S(uint32_t i){ return int32_t(((i>>7)&0x1F)|((i>>25)<<5)); }

    bool is_spill_like(uint32_t ins){
        uint32_t opc = ins & 0x7F;
        if(opc==0b0000011 || opc==0b0100011){      // LOAD/STORE
            int32_t off = (opc==0b0000011)? imm_I(ins) : imm_S(ins);
            return rs1(ins)==2 && std::abs(off) < 256;
        }
        return false;
    }

    void decode_execute(uint32_t ins);
    void op_load(uint32_t), op_store(uint32_t), op_opimm(uint32_t),
         op_op(uint32_t), op_opimm32(uint32_t), op_op32(uint32_t),
         op_branch(uint32_t), op_jal(uint32_t), op_jalr(uint32_t),
         op_system(uint32_t);

    Memory& mem; uint64_t pc;
    std::array<uint64_t,32> regs{};
    bool running = true;
};

int CPU::spill_penalty = 2;

void CPU::op_load(uint32_t i){
    uint64_t a = regs[rs1(i)] + sx(i>>20,12);
    switch(fn3(i)){
    case 0x0: regs[rd(i)] = sx(mem.load<uint8_t >(a), 8 );  break; // LB
    case 0x1: regs[rd(i)] = sx(mem.load<uint16_t>(a),16 );  break; // LH
    case 0x2: regs[rd(i)] = sx(mem.load<uint32_t>(a),32 );  break; // LW
    case 0x3: regs[rd(i)] =     mem.load<uint64_t>(a);      break; // LD
    case 0x4: regs[rd(i)] =     mem.load<uint8_t >(a);      break; // LBU
    case 0x5: regs[rd(i)] =     mem.load<uint16_t>(a);      break; // LHU
    case 0x6: regs[rd(i)] =     mem.load<uint32_t>(a);      break; // LWU
    default : std::fprintf(stderr,"*** fatal error: bad LOAD\n"); std::exit(1);
    }
}
void CPU::op_store(uint32_t i){
    uint64_t imm=((i>>7)&0x1F)|((i>>25)<<5);
    uint64_t a = regs[rs1(i)] + sx(imm,12);
    switch(fn3(i)){
    case 0: mem.store<uint8_t >(a, regs[rs2(i)]); break;
    case 1: mem.store<uint16_t>(a, regs[rs2(i)]); break;
    case 2: mem.store<uint32_t>(a, regs[rs2(i)]); break;
    case 3: mem.store<uint64_t>(a, regs[rs2(i)]); break;
    default: std::fprintf(stderr,"*** fatal error: bad STORE\n"); std::exit(1);
    }
}
void CPU::op_opimm(uint32_t i){
    uint64_t imm = sx(i>>20,12);
    switch(fn3(i)){
    case 0x0: regs[rd(i)] = regs[rs1(i)] + imm; break;          // ADDI
    case 0x1: regs[rd(i)] = regs[rs1(i)] << (imm & 0x3F); break;// SLLI
    case 0x2: regs[rd(i)] = (int64_t)regs[rs1(i)] < (int64_t)imm; break;// SLTI
    case 0x3: regs[rd(i)] = regs[rs1(i)] < imm; break;           // SLTIU
    case 0x4: regs[rd(i)] = regs[rs1(i)] ^ imm; break;           // XORI
    case 0x5: regs[rd(i)] = (imm>>6) ? int64_t(regs[rs1(i)])>>(imm&0x3F)
                                     : regs[rs1(i)]>>(imm&0x3F); break; // SRLI/SRAI
    case 0x6: regs[rd(i)] = regs[rs1(i)] | imm; break;           // ORI
    case 0x7: regs[rd(i)] = regs[rs1(i)] & imm; break;           // ANDI
    }
}
void CPU::op_opimm32(uint32_t i){
    uint32_t imm = i>>20, rd_=rd(i), rs1_=rs1(i);
    switch(fn3(i)){
    case 0: regs[rd_] = sx32(int32_t(regs[rs1_] + sx(imm,12))); break; // ADDIW
    case 1: regs[rd_] = sx32(int32_t(regs[rs1_] << (imm & 0x1F))); break;// SLLIW
    case 5: regs[rd_] = sx32(int32_t(((imm>>5)? int32_t(regs[rs1_])
                                       : uint32_t(regs[rs1_])) >> (imm&0x1F))); break;
    default: std::fprintf(stderr,"*** fatal error: OP-IMM-32 unimp\n"); std::exit(1);
    }
}
void CPU::op_op(uint32_t i){
    uint32_t f3 = fn3(i), f7 = fn7(i);
    if(f7==1){                          // RV64M (64-bit)
        switch(f3){
        case 0: regs[rd(i)] = int64_t(regs[rs1(i)]) * int64_t(regs[rs2(i)]); break; // MUL
        case 1: regs[rd(i)] = (__int128(int64_t(regs[rs1(i)]))*__int128(int64_t(regs[rs2(i)])))>>64; break; // MULH
        case 2: regs[rd(i)] = (__int128(int64_t(regs[rs1(i)]))*__int128(uint64_t(regs[rs2(i)])))>>64; break;// MULHSU
        case 3: regs[rd(i)] = (__int128(uint64_t(regs[rs1(i)]))*__int128(uint64_t(regs[rs2(i)])))>>64; break;// MULHU
        case 4: regs[rd(i)] = regs[rs2(i)] ? int64_t(regs[rs1(i)]) / int64_t(regs[rs2(i)]) : uint64_t(-1); break;// DIV
        case 5: regs[rd(i)] = regs[rs2(i)] ? regs[rs1(i)] / regs[rs2(i)] : uint64_t(-1); break;          // DIVU
        case 6: regs[rd(i)] = regs[rs2(i)] ? int64_t(regs[rs1(i)]) % int64_t(regs[rs2(i)]) : regs[rs1(i)]; break;// REM
        case 7: regs[rd(i)] = regs[rs2(i)] ? regs[rs1(i)] % regs[rs2(i)] : regs[rs1(i)]; break;            // REMU
        default: std::fprintf(stderr,"*** fatal error: M-ext unimp\n"); std::exit(1);
        }
        return;
    }
    switch(f3){                         // RV64I
    case 0: regs[rd(i)]=(f7==0x20)? regs[rs1(i)] - regs[rs2(i)]
                                  : regs[rs1(i)] + regs[rs2(i)]; break;
    case 1: regs[rd(i)]=regs[rs1(i)]<<(regs[rs2(i)]&0x3F); break;
    case 2: regs[rd(i)]=(int64_t)regs[rs1(i)]<(int64_t)regs[rs2(i)]; break;
    case 4: regs[rd(i)]=regs[rs1(i)] ^ regs[rs2(i)]; break;
    case 5: regs[rd(i)]=(f7==0x20)? int64_t(regs[rs1(i)])>>(regs[rs2(i)]&0x3F)
                                  : regs[rs1(i)]>>(regs[rs2(i)]&0x3F); break;
    case 6: regs[rd(i)]=regs[rs1(i)] | regs[rs2(i)]; break;
    case 7: regs[rd(i)]=regs[rs1(i)] & regs[rs2(i)]; break;
    }
}
void CPU::op_op32(uint32_t i){
    uint32_t rd_=rd(i), rs1_=rs1(i), rs2_=rs2(i), f3=fn3(i), f7=fn7(i);
    if(f7==0x01){                       // RV64M word ops
        switch(f3){
        case 0: regs[rd_]=sx32(int32_t(int32_t(regs[rs1_])*int32_t(regs[rs2_]))); break;// MULW
        case 4: regs[rd_]=sx32(rs2_ ? int32_t(regs[rs1_]) / int32_t(regs[rs2_]) : -1); break;// DIVW
        case 5: regs[rd_]=sx32(rs2_ ? uint32_t(regs[rs1_]) / uint32_t(regs[rs2_]) : uint32_t(-1)); break;// DIVUW
        case 6: regs[rd_]=sx32(rs2_ ? int32_t(regs[rs1_]) % int32_t(regs[rs2_]) : int32_t(regs[rs1_])); break;// REMW
        case 7: regs[rd_]=sx32(rs2_ ? uint32_t(regs[rs1_]) % uint32_t(regs[rs2_]) : uint32_t(regs[rs1_])); break;// REMUW
        default: std::fprintf(stderr,"*** fatal error: OP-32 M unimp\n"); std::exit(1);
        }
        return;
    }
    switch(f3){                        // RV64I word ops
    case 0: regs[rd_]=sx32(int32_t((f7==0x20)? regs[rs1_] - regs[rs2_]
                                            : regs[rs1_] + regs[rs2_])); break;
    case 1: regs[rd_]=sx32(int32_t(regs[rs1_] << (regs[rs2_]&0x1F))); break;
    case 5: regs[rd_]=sx32(int32_t((f7==0x20)? int32_t(regs[rs1_])>>(regs[rs2_]&0x1F)
                                            : uint32_t(regs[rs1_])>>(regs[rs2_]&0x1F))); break;
    default: std::fprintf(stderr,"*** fatal error: OP-32 unimp\n"); std::exit(1);
    }
}
void CPU::op_branch(uint32_t i){
    int32_t imm=((i>>7&1)<<11)|((i>>8&0xF)<<1)|((i>>25&0x3F)<<5)|((i>>31)<<12);
    imm = sx(imm,13);
    bool t=false;
    switch(fn3(i)){
    case 0:t=regs[rs1(i)]==regs[rs2(i)];break;
    case 1:t=regs[rs1(i)]!=regs[rs2(i)];break;
    case 4:t=int64_t(regs[rs1(i)])< int64_t(regs[rs2(i)]);break;
    case 5:t=int64_t(regs[rs1(i)])>=int64_t(regs[rs2(i)]);break;
    default: std::fprintf(stderr,"*** fatal error: branch unimp\n"); std::exit(1);
    }
    if(t) pc=pc-4+imm;
}
void CPU::op_jal(uint32_t i){
    int32_t imm=((i>>21&0x3FF)<<1)|((i>>20&1)<<11)|((i>>12&0xFF)<<12)|((int32_t)i>>31<<20);
    regs[rd(i)] = pc;
    pc = pc-4+ sx(imm,21);
}
void CPU::op_jalr(uint32_t i){
    uint64_t tmp = pc;
    pc = (regs[rs1(i)] + sx(i>>20,12)) & ~1ULL;
    regs[rd(i)] = tmp;
}
void CPU::op_system(uint32_t i){
    if(fn3(i)==0 && (i>>20)==0){ running=false; return; }   // ECALL 0 = exit
    std::fprintf(stderr,"*** fatal error: SYSTEM unimp\n"); std::exit(1);
}
void CPU::decode_execute(uint32_t ins){
    switch(ins & 0x7F){
    case 0b0000011: op_load(ins);   break;
    case 0b0100011: op_store(ins);  break;
    case 0b0010011: op_opimm(ins);  break;
    case 0b0110011: op_op(ins);     break;
    case 0b0011011: op_opimm32(ins);break;
    case 0b0111011: op_op32(ins);   break;
    case 0b1100011: op_branch(ins); break;
    case 0b1101111: op_jal(ins);    break;
    case 0b1100111: op_jalr(ins);   break;
    case 0b0110111: regs[rd(ins)] = sx(ins & 0xFFFFF000ULL,32); break; // LUI
    case 0b0010111: regs[rd(ins)] = pc-4 + sx(ins & 0xFFFFF000ULL,32); break;// AUIPC
    case 0b1110011: op_system(ins); break;
    default: std::fprintf(stderr,"*** fatal error: unknown opcode\n"); std::exit(1);
    }
}

// main calling for the script.....
int main(int argc,char** argv)
{
    if(argc < 2){
        std::fprintf(stderr,"usage: %s prog.elf\n", argv[0]); return 1;
    }
    Memory mem;
    uint64_t entry = load_elf(argv[1], mem);
    CPU cpu(mem, entry);
    while(cpu.step()) ;
    std::printf("cycles: %llu\n",
                (unsigned long long)cpu.get_cycles());
    return 0;
}
